nasa/cFS-GroundSystem

Guide-GroundSystem.txt, Subsystems/Commands-Telemetry.txt
Replaced invalid apostrophes and hyphens with proper characters.
=> Closes #14 - replaced non-ascii characters

Subsystems/cmdUtil/cmdUtil.c
Fixes #37 
1. Built with "-Wall -Wstrict-prototypes -std=c99 -pedantic -Wcast-align -D_XOPEN_SOURCE=600"
1. Executed cfe-core
1. Sent reset and noop commands from cmdUtil
No more build warnings
**System(s) tested on:**
- OS: Ubuntu 16.04
- Versions: master bundle with this change
N/A
**Contributor Info**
=> Fix #37: Clean up build warnings

Subsystems/cmdUtil/cmdUtil.c
Fixes #37 
1. Checked out bundle with ic-20191115 branches 
1. make ENABLE_UNIT_TESTS=TRUE SIMULATION=native prep
1. make
1. make install
1. make test
Built without warnings, all tests passed except osal_timer_UT (nominal result on linux)
executed cfe, successful startup with no warnings
Confirmed passed CI (with cppcheck enforced!)
No functional changes, cleans up build warnings.
**System(s) tested on:**
- cFS dev server
- OS: Ubuntu 16.04
- Versions: bundle ic-20191115 branch
None
**Contributor Info**
=> Integration Candidate 20191115

GroundSystem.py, RoutingService.py
Updated GroundSystem.py and RoutingService.py scripts needed to upgrade to Python 3.
Fixes issue #35 
1. Build steps: 
a. Need to install Python 3 (if not already installed)
b. May need to install zmq and pyqt4 for python3
- sudo apt-get install python3-zmq
- sudo apt-get install python3-pyqt4
2. Execution steps: 
To run type - python3 GroundSystem.py
No behavior changes are expected.  However there was an additional unreported issue with the commanding interface  - where upon startup it would intermittently issue the following error - "Ignored socket error" resulting in the inability to command.  This issue was also fixed when updating the scripts.
**System(s) tested …
=> Adding Python 3 compatibility #35

GroundSystem.py, RoutingService.py
Fix #35
1. Checked out all IC 20191230 branches
1. Built and ran cFS unit tests and OSAL coverage (vxworks and shared)
1. All passed (although osal_timer_UT occasionally still fails due to a test issue)
1. Make cmdUtils where cFS-GroundSystem expects it
1. cd tools/cFS-GroundSystem/Subsystems/cmdUtil
1. make
1. Started Ground system
1. python3 GroundSystem.py
1. Enabled commands to 127.0.0.1
1. Confirmed telemetry packets received
1. Sent ES and TIME noop commands, confirmed noop message from cFS on Port 1
1. Sent ES power on reset and observed cFS exit
See related pull requests
- cFS Dev Server 2
- Versions: ic-20191230 branches
N/A …
=> Integration Candidate 20191230

GroundSystem.py, RoutingService.py, Subsystems/cmdGui/CommandSystem.py, Subsystems/cmdGui/HTMLDocsParser.py, Subsystems/cmdGui/Parameter.py, Subsystems/cmdGui/UdpCommands.py, Subsystems/tlmGUI/EventMessage.py, Subsystems/tlmGUI/GenericTelemetry.py, Subsystems/tlmGUI/TelemetrySystem.py
Fix #52, Python3 and tlm processing
1. Launched cFS Ground System (GroundSystem.py)
2. Started Command and Telemetry System
3. Enabled Tlm on 127.0.0.1
4. Opened Event Message and Executive Services telemetry pages - verified telemetry nominal.
5. Sent a ES No-OP.
6. Verified that Event Message tlm page updated successfully and that the command counter on the Executive Services Tlm page incremented.
All of the scripts should now be updated to work with python 3.
Telemetry System should now work/be able to be used to view telemetry.
Oracle VM VirtualBox
OS: ubuntu-19.10
Version: cFE 6.7.3.0; OSAL 5.0.3.0; PSP 1.4.1.0
**Contributor Info**
Dan Knutsen
GSFC/NASA
=> Fix #52, Python3 and tlm processing

Subsystems/cmdUtil/cmdUtil.c
Fixes issue #40 
Temporary/quick fix for issue 40.
1. Recreated issue as stated 
2. Updated cmdUtil...followed by nominal build process
3. Successfully sent a number of commands that contain --word parameter
Commands utilizing --word parameter will now work
**System(s) tested on:**
Oracle VM VirtualBox
OS: ubuntu-19.10
Version: cFE 6.7.3.0; OSAL 5.0.3.0; PSP 1.4.1.0
**Contributor Info**
Dan Knutsen
GSFC/NASA
=> Fix #40, GUI Command definitions

GroundSystem.py, RoutingService.py, Subsystems/cmdGui/CommandSystem.py, Subsystems/cmdGui/HTMLDocsParser.py, Subsystems/cmdGui/Parameter.py, Subsystems/cmdGui/UdpCommands.py, Subsystems/cmdUtil/cmdUtil.c, Subsystems/tlmGUI/EventMessage.py, Subsystems/tlmGUI/GenericTelemetry.py, Subsystems/tlmGUI/TelemetrySystem.py
Fix #40, fix #52
1. Current CI passes
1. Enhanced CI in #40 passes debug/with deprecated elements testing
- Now excepts --word as alias to --long
- Fully converted to python3 and fixed tlm subscription
- CI: Ubuntu 18.04, IC bundle
N/A
N/A
=> Integration Candidate 20200121

Guide-GroundSystem.txt, README.md, Subsystems/cmdGui/CHeaderParser-hdr-paths.txt, Subsystems/cmdGui/CHeaderParser.py
Fix #50 
See PR #56 
Bundle CI, see https://github.com/nasa/cFS/pull/58
See PR #56 
CI Ubuntu:Bionic
Daniel Knutsen, NASA-GSFC
Gerardo E. Cruz-Ortiz, NASA-GSFC
=> Integration Candidate 2020-03-18

Subsystems/cmdUtil/cmdUtil.c
Implement CCSDS command secondary header such that it is endian agnostic.  Really just sets command code appropriately.
Fix #65 
1. Tested via bundle CI (including non-zero command send to reset)
1. Also tested locally with enabling TO via cFS-GroundSystem
This covered both direct cmdUtil call and cFS-GroundSystem use.
Cmd code (and checksum) are always in the same place (matches GSFC spec for command secondary header)
- Hardware: CI and cFS Dev Server
- Versions: test bundle with this change and https://github.com/nasa/cFE/pull/568 in cfe
See also https://github.com/nasa/cFE/pull/568, these two should be …
=> Fix #65, CCSDS Command Secondary Header Endian Agnostic

Subsystems/cmdUtil/cmdUtil.c
Fix possible non-truncated string in option parsing.
This generated a warning in GCC9.
Fixes #76 
Build code with default config, SIMULATION=native BUILDTYPE=release on GCC 9.3.0.
Confirm successful build with no warning.
No impact to behavior
Ubuntu 20.04 LTS 64 bit
Joseph Hickey, Vantage Systems, Inc.
=> Fix #76, warnings on strncpy

Subsystems/tlmGUI/EventMessage.py
Fix #83  - added event type and ID to event message display
1. Brought up event display
2. Induced known events to ensure that the event type and ID are being displayed
Oracle VM VirtualBox
OS: ubuntu-19.10
Versions: cFE 6.7.14.0, OSAL 5.0.13.0, PSP 1.4.9.0
Dan Knutsen
NASA/Goddard
=> Fix #83, Add event type and ID to message

.gitignore, GroundSystem.py, _version.py
Resolve #112 
Ran ground system on OSX and confirmed version printout on stdout 
Prints version number on startup
OSX 10.14.6
Python 3.8.3 
None
None
Gerardo E. Cruz-Ortiz, NASA-GSFC
=> Resolve #112, add build number and baseline

README.md, Subsystems/cmdGui/Parameter.py, Subsystems/cmdGui/UdpCommands.py, Subsystems/tlmGUI/TelemetrySystem.py, _version.py
Fix #118
Bundle CI - https://github.com/nasa/cFS/pull/119/checks
PR #119 - Removes unused code/packages.
Ubuntu
Part of nasa/cfs#119
None
Jacob Hageman, NASA-GSFC
=> Integration Candidate 2020-07-29

Subsystems/Commands-Telemetry.md, Subsystems/Commands-Telemetry.txt
Documentation fixes.
Christopher.D.Knight@nasa.gov
=> fix #125 - multiple typo fixes, etc in Commands-Telemetry.txt

Subsystems/cmdUtil/SendUdp.c
Fix #93 - replaces old code that caused a cast-align warning when strict
- refactored and removed unnecessary code while also following recommended model for getaddrinfo.
- removed old windows support/defines/etc (likely not tested for years, no longer supported).
Built, sent successful command to cFE
No more warning, less fragile.
- Versions: bundle main + this commit
None.
None.
=> Fix #93, Refactor and resolve cast align warning

Subsystems/cmdUtil/cmdUtil.c
Closes #128 
Reduce the size of the strncpy so that it ensures there's a null byte at the end of the string buffer.
make install, make test
Debian 10.5
Christopher.D.Knight@nasa.gov
=> Fix #128, strncpy should result in null term

README.md, Subsystems/cmdUtil/SendUdp.c, Subsystems/cmdUtil/cmdUtil.c, _version.py
Fix #93 
Fix #128 
Bundle CI - https://github.com/nasa/cFS/pull/136/checks
PR #130 - Replaces old code that caused a cast-align warning when strict.  Refactored and removed unnecessary code while also following recommended model for `getaddrinfo`.  Removed old windows support/defines/etc (likely not tested for years, no longer supported).
PR #129 - Reduce the size of the `strncpy` so that it ensures there's a null byte at the end of the string buffer.
Ubuntu - CI
https://github.com/nasa/cFS/pull/136
Jacob Hageman, NASA-GSFC
Chris Knight, NASA-ARC
=> Integration Candidate: 2020-09-02

Subsystems/cmdGui/CHeaderParser.py
Fixes #131 addressing issues raised by end user
No sample input available so no testing performed; will need to be tested
Fix the issues raised in #131 
Leor Bleier GSFC\Code 582
=> Fix #131 - updated CHeaderParser.py to address specific issues

README.md, Subsystems/cmdGui/CHeaderParser.py, _version.py
Fix #131 
Bundle CI - https://github.com/nasa/cFS/pull/139/checks
PR #132  -  Updated CHeaderParser.py to address specific issues.
Ubuntu - CI
https://github.com/nasa/cFS/pull/139
Leor Bleier, NASA-GSFC
=> Integration Candidate: 2020-09-09

SECURITY.md
Fix #142 
Created a draft of a security policy markdown file for cFS-GroundSystem. The purpose of a security policy is to inform users on how to submit bugs or vulnerabilities. It is ideal to include a section for supported versions.
Optional sections that may be included:
- What to expect security-wise such as what type of testing is done
- Address privacy concerns
- Supported versions
- License
- Known vulnerabilities
References to Public Security Policies:
https://github.com/thanos-io/thanos/security/policy
https://github.com/minhealthnz/nzcovidtracer-app/security/policy
https://github.com/odoo/odoo/security/policy
Ariel Adams, ASRC Federal
=> Fix #142, Create Security Policy

Subsystems/cmdUtil/cmdUtil.c
Fix #144 - rounds header up to match nasa/cFE#1077
Sent command to cFE with extended header, confirmed round up worked.
Breaking change, behaves the same if cFE is run with nasa/cFE#1077
- Versions: Bundle main + nasa/cFE#1077 + this commit
None
None
=> Fix #144, Pad cmdUtil header to 64 bit boundary

GroundSystem.py
Fix #147 - rounds headers up to match nasa/cFE#1077
Tested cmds and tlm with a cFE using extended headers and without.  Worked.
Breaking change, behaves the same if cFE is run with nasa/cFE#1077
- Versions: Bundle main + nasa/cFE#1077 + this commit
None
None
=> Fix #147, Pad GUI headers to 64 bit boundary

GroundSystem.py, README.md, SECURITY.md, Subsystems/cmdUtil/cmdUtil.c, _version.py
Fix #144, Pad cmdUtil header to 64 bit boundary
Fix #147, Pad GUI headers to 64 bit boundary
Fix #142, Create Security Policy
See <https://github.com/nasa/cfs/pulls/177/checks>
PR #143 - Documentation: Add `Security.md` with instructions to report vulnerabilities
PR #145 - **Breaking change**, CmdUtil, Rounds header up to match <https://github.com/nasa/cFE/pull/1077>
PR #148 - **Breaking change**, GUI, Rounds header up to match <https://github.com/nasa/cFE/pull/1077>
Ubuntu 18.04
Part of <https://github.com/nasa/cfs/pulls/177>
None
@ArielSAdamsNASA 
@skliper
=> cFS-GroundSystem Integration candidate: 2021-01-19

.github/workflows/codeql-build.yml
Fix #153 - adds CodeQL analysis
Differences from bundle - just builds cmdUtil, has timeout
Ran on fork
Adds Code QL analysis on push to main and pull requests (to main)
CI
None
None
=> Fix #153, Add CodeQL analysis to workflow

Subsystems/cmdUtil/SendUdp.c, Subsystems/cmdUtil/cmdUtil.c
Fix #157 - applies formatting, removed an "if" that didn't do anything and initialized the reported IP to UNKNOWN if `getnameinfo` doesn't work.
Built and ran cmdUtil
Reports `UNKNOWN` if getnameinfo doesn't work.
- Versions: cFS Bundle main + this commit
None
None
=> Fix #157, Apply formatting

Subsystems/cmdGui/CHeaderParser.py
Fix #155 - removes unnecessary type translations from CHeaderParser.py (also removes broken "double")
Requesting test by @JackNWhite
Spot checked processing of int32's so at least the pattern is ok (and runs)
`uint64` will no longer get translated by `CHeaderParser` into the unsupported `double` type
cFS Dev Server, Ubuntu 18.04
None
None
=> Fix #155, Remove unnecessary type translations

README.md, Subsystems/cmdGui/CHeaderParser.py, _version.py
Fix #155, Remove unnecessary type translations
See <https://github.com/nasa/cFS/pull/193/checks>
PR #156 - Removes unnecessary type translations from `CHeaderParser.py` and broken `double` option. `uint64` will no longer get translated by `CHeaderParser` into the unsupported `double` type
Ubuntu 18.04
Part of <https://github.com/nasa/cFS/pull/193>
None
@skliper
=> cFS-GroundSystem Integration candidate: 2021-02-23

SECURITY.md
Fix #163
Updated the Security Policy to include the type of testing done for cFS-GroundSystem or the cFS bundle under a new section titled "Testing". Provided a disclaimer that under the Apache license, liability is not provided. 
Added that security reports should be emailed. 
Users should now be aware of the type of testing cFS-GroundSystem or the cFS bundle undergoes. 
References: 
https://github.com/thanos-io/thanos/security/policy
https://github.com/phpMussel/phpMussel/security/policy
https://github.com/timberio/vector/security/policy
Ariel Adams, ASRC Federal
=> Fix #163, Add Testing Tools to the Security Policy

Subsystems/tlmGUI/cfe-sb-hk-tlm.txt, Subsystems/tlmGUI/cfe-tbl-hk-tlm.txt
A clear and concise description of what the contribution is.
- The telemetry pages for SB and TBL do not load when selected to open as it creates a buffer error. (Issue #165)
- Fix: Updates values to correct values for each subsystem
1. Ran the ground system: make (in cmdUtil)
2. python3 GroundSystem.py
3. Started Telemetry (with TLM enabled)
4. Opened Tlm for TBL and SB
5. Additionally tested rest of TLM system
- Will allow for the TBL and SB tlm pages to open.
RPi 3B+
OS: Raspberry Pi OS, formally Raspbian
Versions [Bundle main]
Evan Fitzgerald (Personal)
=> Fix #165, Updated TBL and SB tlm for an operational TLM display

CONTRIBUTING.md
Fix #169 
Added a contributing guide that links to the main cFS contributing guide. 
Users should be able to view the contributing guide contents easily from the cFS-GroundSystem repo. 
Ariel Adams, ASRC Federal
=> Fix #169, Add Contributing Guide

GroundSystem.py, requirements.txt, setup.py
A clear and concise description of what the contribution is.
- Include explicitly what issue it addresses [e.g. Fixes #123 ]
A clear and concise description of how this contribution will change behavior and level of impact.
- Behavior Change: (The user will be able to type command 'startg' and start the ground system from anywhere on the system)
- OS: [macOS Catalina v 10.15.7]
I installed the package with command pip3 install -e relative/path/to/cfs-groundsystem/
In GroundSystem.py there is a variable name ROOTDIR, in order for this command to work, the ROOTDIR has been changed to the path of the file being executed.
The original path was:
ROOTDIR = …
=> Fix #123, create package for cfs-groundsystem

setup.py
A clear and concise description of what the contribution is.
-Changing executable command from 'startg' to 'cFS-GroundSystem'
-Changing version to be the version stated in version.py
made sure new executable command works 
Changing executable command from 'startg' to 'cFS-GroundSystem'
- Hardware: MacBook Pro 
- OS: macOS Big Sur
- Versions: 11.2.3
Zachary Gonzalez - Personal
=> fix #172, updating executable name and version in setup.py

Guide-GroundSystem.md, setup.py
A clear and concise description of what the contribution is.
- Adding executable installation instructions to Guide-GroundSystem.md
Since a requirements.txt file is being added it could possibly simplify installs for future users by adding in the pyQT5 and the pyZMQ packages.
Zachary Gonzalez - Personal
=> Fix #173, Add executable install guide

Guide-GroundSystem.md, README.md, setup.py
Fix #172, update executable name and version in setup.py (#174)
Changes executable command from 'startg' to 'cFS-GroundSystem'
Changes version to be the version stated in version.py
Fix #173, Add executable install guide 
Adds executable installation instructions to Guide-GroundSystem.md
Part of <https://github.com/nasa/cfs/pull/248>
cFS-GroundSystem checks <https://github.com/nasa/cFS-GroundSystem/pull/178/checks>
cFS Bundle Checks <https://github.com/nasa/cfs/pull/248/checks>
@zachar1a
=> cFS-Ground System Integration candidate: 2021-04-20

.github/workflows/codeql-build.yml
Fix #179 
Added the duplicate jobs action to avoid duplicate jobs from running. Added a separate job for coding standard queries. Created two configuration files, one for default queries and security queries and another for jpl rules. Removed push on main branch so when users push code to their forked repos, the workflow runs. Added main branch to pull request, so CodeQL runs on pull request made in the main branch. This is the same logic used in the cFS bundle repo. 
Testing done on cFE forked repository, ArielSAdamsNASA/cFE which used the same files, but with different configuration paths.
Jobs were failing when the entire path of the configuration file were not used. Have to use nasa/cFE/.github/codeql/config-name@branch-name. The …
=> Fix #179, Implement Coding Standard in CodeQL

Subsystems/cmdUtil/es-delete-app.sh, Subsystems/cmdUtil/start-test-app.sh
Fix #181 - added the script
Ran the script, ensured the test app was executed and tests pass.
None
- Hardware: Intel I5/Docker
- Versions: Bundle main + this commit
None
None
=> Fix #181, Add test start command script for cmdUtil

Subsystems/tlmGUI/GenericTelemetry.py
- Fixes #149 
- The problem was that itemStart and tlmOffset were initialized and declared in a try-catch block and if it fails, it could be that itemStart or tlmOffset is not available.
1. IDE stops throwing this warning after the change
- stop throwing an UnboundLocalError for some people
Paul Oberosler, Individual
=> Fix #149, * might be referenced before assignment

.gitignore
Structured .gitignore
- Fixes #189 
1. made a commit with the new .gitignore
Paul Oberosler, Individual
=> Fix #189, Virtualenv and Pipenv .gitignore support

.gitignore, Guide-GroundSystem.md, README.md, RoutingService.py, SECURITY.md, Subsystems/cmdGui/CHeaderParser.py, Subsystems/cmdGui/CommandFiles/cfe__es__msg_8h, Subsystems/cmdGui/Parameter.py, Subsystems/cmdGui/ParameterFiles/struct_c_f_e___e_s___c_d_s_reg_dump_rec__t, Subsystems/cmdGui/ParameterFiles/struct_c_f_e___e_s___hk_packet__t, Subsystems/cmdGui/ParameterFiles/struct_c_f_e___e_v_s___app_data_cmd__t, Subsystems/cmdGui/ParameterFiles/struct_c_f_e___e_v_s___log__t, Subsystems/cmdGui/command-pages.txt, Subsystems/cmdUtil/SendUdp.c, Subsystems/cmdUtil/cmdUtil.c, Subsystems/cmdUtil/readme.txt, _version.py
PR #190
- Fix #189, Virtualenv and Pipenv .gitignore support
PR #194
- Fix doc, comment, and message typos 
cFS-GroundSystem Checks <https://github.com/nasa/cFS-GroundSystem/pull/195/checks>
cFS Bundle Checks <https://github.com/nasa/cFS/pull/348/checks>
See PRs
Ubuntu
Part of <https://github.com/nasa/cFS/pull/348>
None
@pavll
@thnkslprpt
=> cFS-GroundSystem Integration candidate: 2021-08-31
